apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tutorial
  labels:
    app: java-tutorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-tutorial
  template:
    metadata:
      labels:
        app: java-tutorial
    spec:
      containers:
      - name: java-tutorial
        image: ghcr.io/samarth0157/java-tutorial:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:  # Reference the secret here
      - name: ghcr-secret
