apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-tutorial-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Specifies the NGINX ingress controller
  rules:
  - host: java-tutorial.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-tutorial  # Must match the Service name
            port:
              number: 80
